#!/usr/bin/env python
# coding: utf-8

'''
MDP for modeling autoscaling in a K8s enviornment for arbitrary number of service units and buffer sizes, assuming instantaneous scaling up/down at thresholds

We consider a model similar to that of Tournaire et al 2023, where scaling is optimized according to minimizing SU activation/deactivation costs, rejection costs due to full buffer, and costs of servicing 
SUs and holding requests. Similar models are considered in alternative settings by the same research group for multi-server queue models.

We consider the model as a discrete time discounted MDP, with a hysteresis policy assumed for scaling up/down
'''

import marmote.core as mco
import marmote.markovchain as mch
import marmote.mdp as md
import numpy as np

'''
 **System Parameters**
 
# N - Size of the system buffer, for **N**umber of reqeusts
# M - Maximum number of Service Units (SUs) or **M**achines permitted (choose M to avoid confusion with the system state space) 

# LAM - Poisson arrival rate of requests
# MU - service rate of an individual SU; SUs are homogenous by design and thus have identical service rate

# Costs fall into two cateogries, instantaneous costs paid when the action occurs, and accumulated costs paid at each time step 

# Instantaneous costs:  
# CA - activation cost of new SU
# CD - deactivation cost of unneeded SU
# CR - rejection cost of request entering system to full buffer

# Accumulated costs: 
# CS - cost per time unit of serviceing each SU
# CH - cost per time unit of holding each request

# GAMMA - factor for discounted MDPs, gamma closer to 1 emphasizes future reward, gamma closer to 0 emphasizes short term gain ('greedy' algorithm)

# EPSILON - convergence threshold for MDP application
# MAXITER - maximum number of iterations to run MDP solution for, irrespective of EPSILON speficiation

'''

# build dictionary to hold model values
system = dict()
system['N'] = 5
system['M'] = 3
system['LAM'] = 2.0
system['MU'] = 1.0
system['CA'] = 0.75 # 2.0  
system['CD'] = 0.75 # 2.0
system['CR'] = 4.0 # 10.0
system['CS'] = 1.0 # 5.0
system['CH'] = 1.0 # 5.0
system['GAMMA'] = 0.1
system['EPSILON'] = 0.0001
system['MAXITER'] = 1000
print(system)

'''
**Building the state and action spaces**

# States take the form (m,n) for 1 <= m <= M, 0 <= n <= N
# Due to python indexing, the number of machines is offset by 1, and index "0" represents the base state of 1 SU, index "1" represents 2 SUs, etc.
# Similarly, the buffer size must be incremented by 1 to ensure the correct buffer size is reflected in the states 


# An action takes the form *{m-1,m,m+1}* for 1 <= m <= M, representing the number of SUs active following the action;
# In the event the controller takes action -1 when m = 1, or action 1 when m = M, the special cases are defined s.t. the number of SUs do not change
# But the action remains technically available to take (it simply costs extra resources due to wasted effort) 
'''

dims=np.array([system['M'],system['N']+1])
# print(dims) 
states= mco.MarmoteBox(dims)
#
actions=mco.MarmoteInterval(-1,1)

'''
print("Number of states",states.Cardinal())
print(states.Enumerate())
print("Number of actions",actions.Cardinal())
print("actions",actions)
'''

'''
**Building the Transition matricies**

# We define a function which computes a transition matrix associated with the action such that action index is index_action; 
# see also pyMarmote App_Lesson2.py for an example

# In each state, there are two events which can occur: system arrivals, and system depatures

'''

# name coordinate indicies for ease of reading
SU = 0
QUEUE = 1

def newSU(curSU,act,model):
    '''
    Takes the current SUs and returns the new SUs following the action taken
    generally newSU = curSU + act where act in {-1,0,1}, however if curSU = 1 or curSU = M must handle edge case appropriately

    As noted above, we assume in these cases that if controller attempts to scale down/up respectively, we return to the same level; 
    for the purposes of the cost matrix we still inccur actvation/deactivation stage costs related to wasted effort
    '''
    mNew = max(min(curSU+act,model['M']),1)
    return mNew 

def fill_in_matrix(actionBuffer,stsp,model):
    '''
    Generates the transition matrix associated with the given action
    actionBuffer - Buffer containing the action taken within the action space interval
    stsp - the state space generated by buffer size and SU size
    model - the dictionary specifying the system model

    returns P - the transition matrix of rate of transitions from each state to each other eligible state
    '''
    action = actionBuffer[0]
    # print("action",action)
    # define the states
    stateO = np.array([0,0]) #  Origin state, initialize to first state, corresponding to state (0,1) (empty buffer, 1 SU - note index offset)
    stateD = np.array([0,0]) # Destination state, dummy initialization
    afteraction = np.array([0,0]) # state after action taken, dummy initialization 
    # define transition matrix, intiialize to empty matrix size of the state space
    P=mco.SparseMatrix(stsp.Cardinal()) 
    #browsing state space
    stsp.FirstState(stateO)
    for indexO in range(stsp.Cardinal()):
        # compute the state after the action
        afteraction[QUEUE] = stateO[QUEUE]
        afteraction[SU] = newSU(stateO[SU]+1,action, model)-1 # account for -1 indexing offset
        # then detail all possible transactions
        ## Arrival (increase the number of customers by 1 with rate lambda)
        # B-D chain, can only have arrivals entering the system if the buffer is not full
        if (afteraction[QUEUE] < model['N']):
            stateD[QUEUE]=afteraction[QUEUE]+1
            stateD[SU]=afteraction[SU]
            #compute the index of the destination
            indexD = stsp.Index(stateD)
            # fill in the entry
            P.setEntry(indexO,indexD,model['LAM'])
        ## Depatrue, decrease the number of custoemer by 1 with rate min(n,m)*mu
        # B-D chain, cannot have a depature from an empty system
        if (afteraction[QUEUE] > 0) :
            stateD[QUEUE] = afteraction[QUEUE]-1
            stateD[SU] = afteraction[SU]
            # compute index of the destination
            indexD = stsp.Index(stateD)
            '''
            fill in the entry; transition rate depends on the base rate, the number of Service Units, AND the number of customers
            service rate can be no more than num SU * mu, however if the queue is smaller than the number of machines, then clearly service rate is limited by the queue size 
            '''
            P.setEntry(indexO,indexD,model['MU']*min(afteraction[QUEUE],stateD[SU]+1)) # account for zero indexing for number of SUs
        # get next state
        stsp.NextState(stateO)
    # print(P)
    return P

'''
**Cost Matrix**

# We define now a function to fill in the cost matrix. 
 
# Instantaneous Costs are:   
# Costs of activations = *max(action1-k1,0) \* Ca + max(action2-k2,0) \* Ca*  
# Costs of deactivations = *max(K1-action1,0) \* Cd + max(K2-action2,0) \* Cd*  
# rejection cost= *Cr \* lambda/Lambda(s,a)* in states where *m1=B* added by  *Cr \* action1 mu/Lambda(s,a)* in states where *m2=B*.  
# *Lambda(s,a)* is the total rate. It is equal to *lambda + action1 \* mu + action2 \* mu* .

# Accumulated Costs are:  
# (number of customers in the system)Ch = n*Ch   
# (number of active SUs) = m*Cs

# Note that because we "allow" scaling down at m = 1/scaling up at m = M (we simply return to the previous level), we impose stage costs for the wasted work, but not
# an infinite cost corresponding to infeasible actions. This could change in a future version of the script depending on further determinations of model behavior.  
'''



def fill_in_cost(stsp,atsp, model):
    '''
    Defines the cost matrix containing the stage cost associated with a given state, action pair
    stsp - the state space generated by buffer size and SU size
    atsp - the action space interval
    model - the dictionary containing the system model

    returns R - the matrix of costs for each pair (s,a) of states and actions, where states are indexed lexiographically (i.e., all 0 SU states first, then all 1 SU states, etc.)
    '''
    # Create the matrix space
    R= mco.FullMatrix(stsp.Cardinal(),atsp.Cardinal())
    # define the states and actions
    stateBuffer = np.array([0,0]) # initialize to state (1,0) - 1 SU, empty buffer; indexed as (0,0) due to Python index rules
    stsp.FirstState(stateBuffer) 
    # browse state space
    for indexS in range(stsp.Cardinal()):
        # print("##State",stateBuffer)
        # within state, browse action space
        actionBuffer = atsp.StateBuffer()
        atsp.FirstState(actionBuffer)
        for indexA in range(atsp.Cardinal()):
            act = actionBuffer[0] # retrieve the action associated with the current buffer
            # print("---Action",act,end='  ')
            mprime = newSU(stateBuffer[SU]+1,act, model) # number of SUs after action taken, determines total rate and cost of active SUs
            totalrate = model['LAM'] + model['MU']*min(mprime,stateBuffer[QUEUE]) # total rate, arrivals + service rate following action
            # print("totalrate=",totalrate,end=' ')
            activationcosts = model['CA']*max(0,act) # activation cost, paid out instantaneously upon SU activation
            deactivationcosts = model['CD']*abs(min(0,act)) # deactivation cost, paid out instantaneously upon SU activation
            rejectioncosts = model['CR']*(stateBuffer[QUEUE]//model['N'])*model['LAM'] / totalrate # rejection cost, incurred if there is arrival to a full buffer
            instantaneouscosts = activationcosts + deactivationcosts + rejectioncosts
            requestcosts = stateBuffer[QUEUE]*model['CH']/totalrate
            serviceunitcosts = mprime*model['CS']/totalrate
            accumulatedcosts = requestcosts + serviceunitcosts # accumulated costs, costs of running 
            # print("Activation=",activationcosts," Deactivation=",deactivationcosts," Rejection=",rejectioncosts,end= ' ')
            # print("ServiceUnits=",serviceunitcosts," Requests=",requestcosts)
            R.setEntry(indexS,indexA,accumulatedcosts+instantaneouscosts)
            atsp.NextState(actionBuffer)
        stsp.NextState(stateBuffer)
    # print (R)    
    return R

'''
**Build continuous time MDP** 

# Build all the transition matrix corresponding to each action
# As the actions are defined as the interval {-1,0,1}, representing the (attempted) change in number of SUs
# The corresponding indicies k = {0,1,2} or action+1

'''

print("building Transition Matricies")
trans=list()
actionBuffer = actions.StateBuffer()
actions.FirstState(actionBuffer)
for indexA in range(actions.Cardinal()):
    trans.append(fill_in_matrix(actionBuffer,states,system))
    print("---Matrix kth=",indexA, "filled in")
    actions.NextState(actionBuffer)

'''
# Fill in the cost matrix corresponding to each (state,action) pair, where states are labeled lexiographically
'''

print("building Cost Matrix")
Costs=fill_in_cost(states,actions,system)


# Build the MDP

print("Building Continuous Time Discounted MDP")
ctmdp=md.ContinuousTimeDiscountedMDP("min",states,actions,trans,Costs,system['GAMMA'])
print(ctmdp)


# Transform the Continuous Time MDP to a Discrete Time MDP by applying uniformization factor; determined by applying the maximum transition rate
# In the case of our model, this equals the arrival rate LAM plus service rate MU times min(M,N) - while the maximum number of SUs allowed is the
# nominal limiting factor for service rate, if the queue size limit is smaller than maximum number of SUs permitted, customers cannot be servied faster than this limit


ctmdp.UniformizeMDP()
print("Rate of Uniformization",ctmdp.getMaximumRate())
print(ctmdp)


# Solve MDP, using Value Iteration, and print the solution
print("Solving using Value Iteration")
optimum=ctmdp.ValueIteration(system['EPSILON'],system['MAXITER']) 
print(optimum)

'''
# Structural Analysis

# The structural analysis is mainly related to the policy handling. 
# 
# 1. Check property of the MDP by building a Markov Chain Associated with a policy
# 2. Check property of the value function 

# Essentially, using associated Markov Chain analysis to validate MDP results; however as multichain properties are solely valid for average mulitchain criteria
# as opposed to discounted criteria, we build a special policy building off the examples provided in the pyMarmote package examples


policy=md.FeedbackSolutionMDP(states.Cardinal())



Fill in the policy. Define the policy as follows per the MC best-per-level hysteresis search algorithms from Tournaire 2021:

Deactivate if 
Activate if

Otherwise, keep machines the same




state=states.StateBuffer()
states.FirstState(state)
for indexS in range(states.Cardinal()):
    if(etat[0]==(model['B1']-1) or etat[2]==(model['B2']-1) ):
        # Activate SU, action = 1, index = 2
        indexA = 2
    elif :
        # deactivate SU, action = -1, index = 0
        indexA = 0
    else:
        # keep SUs the same, action = 0, index = 1
        indexA = 1
    policy.setActionIndex(indexS,indexA)
    states.NextState(etat)
print(policy)


# **Build a Markov Chain from a policy**

Mat=ctmdp.GetChain(optimum)
Mat.set_type(mco.DISCRETE)
#*# print(Mat)

initial = mco.UniformDiscreteDistribution(0,states.Cardinal()-1)


# Making the chain

# In[ ]:


chaine = mch.MarkovChain( Mat )
chaine.set_init_distribution(initial)
chaine.set_model_name( "Chain issued from the MDP")


# **Analysis of the transition matrix**

Mat.FullDiagnose()


# **Evaluate the policy**
# 
# Now we can evaluate the policy by the way of the `PolicyCost` method



ctmdp.PolicyCost(policy,0.01,75)
print(policy)


# ### Check if the value function has structural property (convex,monotone)

# This is done by building a specific object `PropertiesValue`.

# In[ ]:


checkValue =  md.PropertiesValue(states)
checkValue.avoidDetail()
monotonicity=checkValue.Monotonicity(optimum)
print("Printing monotonicity property of value function (1 if increasing -1 if decreasing 0 otherwise) : "\
      + str(monotonicity) )

print("Checking convexity")
convexity=checkValue.Convexity(optimum)
print("Printing convexity property of value function (1 if convex -1 concave 0 otherwise) : " + \
      str(convexity))


# The analysis can be made dimension by dimension. Now we check the monotonicty of the first dimension by letting vary the entries with index 0 and keeping the other dimensions fixed.

# In[ ]:


monotonicity=checkValue.MonotonicityByDim(optimum,0)
print("Following dimension 0 monotonicity is",str(monotonicity))


# ### Check if the optimal policy has structural property

# The structural analysis of a policy property is carried out using a `PropertiesValue` object.

# In[ ]:


print("Checking Structural Properties of value")
checkPolicy =  md.PropertiesPolicy(states)

monotonicity=checkPolicy.Monotonicity(optimum)
print("PropertiesPolicy::MonotonicityOptimalPolicy="+str(monotonicity))


# End
'''